### PR TITLE
Replace workflow with process

### PR DESCRIPTION
**Pull request by menski**
This change replaces all occurrences of _workflow_ with _process_ except the term _workflow engine_.

### CODE REVIEW

**Comment by menski** [comment]
@akeller I cherry-picked your glossary changes (https://github.com/camunda-cloud/camunda-cloud-documentation/pull/182/commits/9a54a84c4e775bffd8489ebeaee669a111df8c68) to this branch to not override them, depending on in which order we want to merge these we have to probably up to one of our PRs. Let me know what you prefer. I also don't really know how to review this change, maybe a small sanity check? Happy to discuss the details also face to face if needed.

**Comment by akeller** [comment]
I will do a small sanity check and compare to the list I created previously.

**Review by akeller — COMMENTED** [review]
This looks like it covers all the text, URLs, and file names. Has the UI text already been updated? Some of the screenshots have references to "workflow". 

A few examples:

- the toast/pop up alert "Workflow deployed" on /guides/getting-started/deploy-your-process-and-start-process-instance (img/save-and-deploy-successful.png)
- "Instances by Workflow" on /guides/getting-started/monitor-your-process-in-operate (img/operate-dashboard.png) 
- "Workflow" on /guides/getting-started/monitor-your-process-in-operate (operate-advanced-instances-pong.png)

Unfortunately I think these are going to be harder to find and replace. Hopefully you have a creative idea here :)

**Comment by menski** [comment]
Hey @akeller,

thanks for the review. The UI components like Operate, Tasklist and Console were not updated yet, as we first have to merge the change in the Zeebe repository before we can make progress with that (https://github.com/zeebe-io/zeebe/pull/6455). 

After we updated Tasklist, Operate and Console, I will check the used screenshots in the docs and update them accordingly if needed.

Let me know if you are okay if we merge the current changes already in the `release_0_27` branch, and tackle the screenshots later?

**Comment by akeller** [comment]
@menski Sounds good to me, I'm ok to merge these changes to `release_0_27`. Thank you!

**Pull request merged**
