### PR TITLE
Migrate all 3rd Party Libraries & Dependencies to Reference

### PR DESCRIPTION
**Pull request by akeller**
Moving all 3rd party libraries & dependencies to a single page in the Reference section with tabs for each component. Tabs are indexable and less clicks then navigating to each individual component to review each set of libraries. 

Future updates should include page search/filtering for more robust experience.

### CODE REVIEW

**Comment by akeller** [comment]
@christinaausley no rush here, but can you check my spelling of "dependencies" 😆  I was struggling.

**Comment by akeller** [comment]
**Todo: add redirects**

**Review by christinaausley — APPROVED** [review]
Looks good on my end!

**Comment by akeller** [comment]
@christinaausley can you take another look here? Thank you!

**Review by christinaausley — APPROVED** [review]
Had a hawks eye on each reference of "dependencies" -- looks great!

**Pull request merged**
