### PR TITLE
fix(docs): spelling of 'properties'

### PR DESCRIPTION
**Pull request by rbrenton**

### CODE REVIEW

**Comment by akeller** [comment]
Thanks for your PR @rbrenton! Embarrassingly, I see a few more 😬 . Can I add them to your PR?

**Comment by rbrenton** [comment]
> Thanks for your PR @rbrenton! Embarrassingly, I see a few more 😬 . Can I add them to your PR? 

absolutely!

**Comment by akeller** [comment]
Hmm @rbrenton were you able to sign the CLA?

**Comment by rbrenton** [comment]
> Hmm @rbrenton were you able to sign the CLA?

Done!

**Pull request merged**
