### PR TITLE
Add Micronaut Zeebe Client

### PR DESCRIPTION
**Pull request by tobiasschaefer**
I'm the lead developer of the Micronaut Zeebe Integration Project: https://github.com/camunda-community-hub/micronaut-zeebe-client

Please merge this PR to add the Micronaut Integration to list of community clients.

### CODE REVIEW

**Comment by akeller** [comment]
Thanks @tobiasschaefer! @christinaausley will take a look at this PR to make sure it meets our style guide and we'll get this merged. 

As an FYI we may merge this into our upcoming release branch instead of `master` but we'll handle that ourselves if we take that approach.

**Review by christinaausley — APPROVED** [review]
Very minor adjustments made in latest commit to tighten up the text a bit -- LGTM!

**Comment by tobiasschaefer** [comment]
@akeller : thanks for merging this PR. 

Is my assumption correct that it will be shown at https://docs.camunda.io/docs/apis-clients/community-clients/ on April 12th with the release of Camunda 8?

The changes are on the release-1.4.0 branch. Will you backport the changes to master?

**Comment by akeller** [comment]
@tobiasschaefer We'll merge this release branch into `master` on April 12th. We don't keep version branches in these docs like we do on docs.camunda.org. 

If you'd like, we can also add this to previous Camunda Cloud versions.

**Comment by tobiasschaefer** [comment]
@akeller its okay if it goes live on April 12th considering that people generally look in the latest documentation - but it would also be good to have it in previous Camunda Cloud versions. They are also supported.

**Comment by akeller** [comment]
I'll add this to other versions, but might take me a bit to work through these more urgent PRs 🙂

**Pull request merged**
