### PR TITLE
Documented max payload size

### PR DESCRIPTION
**Pull request by berndruecker**
https://github.com/camunda-cloud/camunda-cloud-documentation/issues/396

### CODE REVIEW

**Comment by berndruecker** [comment]
@npepinpe approved it content-wise: "one small thing, it could be smaller if the user has configured the maxMessageSize to be smaller, but it cannot really be greater as we don't provide a way to configure the gRPC payload size limit."

@berndruecker : "Make sense to me. I don't think we have to discuss the "maxMessageSize" that prominently, as I would consider that the exception that it is configured - while everybody can be hit by this limitation you should be aware of. Thanks a lot!"

**Comment by berndruecker** [comment]
@akeller Good to go from my end

**Comment by akeller** [comment]
FYI Looks like a change in this PR is causing the build issue.

**Comment by berndruecker** [comment]
Wired - but I found a typo that might be it @akeller

**Review by christinaausley — APPROVED** [review]
Adjusted typos and added a note admonition in my latest commit. Looks good on my end.

**Comment by akeller** [comment]
Teamwork makes the dream work 💪

**Pull request merged**
