### PR TITLE
Adding best practices

### PR DESCRIPTION
**Pull request by menski**
Editing for clarity that this is @berndruecker's PR.

> "This is the PR to add the best practices from https://camunda.com/best-practices/

> Note that this also requires a new redirect from `/docs/components/best-practices/` to `/docs/components/best-practices/overview/`

> Once merged I will ping marketing to remove the best practices from cxamunda.com and set the right redirects/rewrites in place."

### CODE REVIEW

**Comment by akeller** [comment]
@berndruecker I noticed the assets folders contain both `png` and `pptx` - can we remove the `pptx` files and store them somewhere internally? 

I really like the structure, although at first it was startling 😅  to see the files were in different folders than in sidebar. But now I get it and I like it! 

Almost every .md file needed adjustments to the frontmatter values. I think Docusuarus is smart enough to ignore the ones it doesn't use, but I removed them in case one day it does decide to use them in some capacity and things break.

I found a Google Spreadsheet in a frontmatter comment for "Sizing your environment". It's only available for Camunda employees, so I removed it. If you'd like to retain this, I would recommend adding it as an `xsl` file to the repo directly.

[Frontmatter](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#markdown-front-matter) should be limited to the following values (for now):
* id (looks like these are being autogenerated which is nice)
* title
* description
* keywords
* tags (I like the use of these, but currently on Best Practices would use them - @christinaausley a good item for you to explore when to use!) 

I did not add additional frontmatter values at this time.

**Comment by berndruecker** [comment]
Thanks a lot for cleaning up! All fine with me.

I wonder what the value of strong PPTX is somewhere else? They are not copied over to the build directory, so they are not available on the built side. So I thought it is most convenient to have them next to the picture - otherwise, you will always search them when editing the practice/picture. We had quite some examples of "who has the sources to this pic" or "how the hell was this created" :-)

if you definitely want to remove it I am happy to do this, but I have no idea where to put them then to be honest. Any ideas?

**Comment by berndruecker** [comment]
@christinaausley as far as I see the current status we need your review as well to merge this. As discussed, would be great if you can approve for now and we catch up with additional copy edits after the release. Would really love to get this live soon this week, as I am on vacation next week. Thx!

**Comment by berndruecker** [comment]
@akeller If I don't get "STOP IT" by end of the day I would merge it tomorrow morning - I really would love to get the ball rolling before my vacation (including redirects by marketing). Sorry for the rush & thx!

**Comment by akeller** [comment]
> if you definitely want to remove it I am happy to do this, but I have no idea where to put them then to be honest. Any ideas?

Leave them in the repo for now. If I start seeing issues with slowness (pptx can really bloat repos) we can move them.

**Review by akeller — APPROVED** [review]
I removed the .vscode file.

This REALLY needs some cleanup to adhere to our style guide, but as long as we get it on our backlog so @christinaausley can prioritize it, I'm ok with merging. 

@berndruecker please coordinate a release with @menski when you are ready to let marketing know to update their redirects. If that needs to happen during US-friendly hours, let me know and I can help.

**Comment by berndruecker** [comment]
Great - thanks @akeller .
Marketing is basically ready to do their changes when the new pages are live. @menski can we target a release tomorrow (wednesday)? If I know an estimated time I will let marketing know

**Comment by menski** [comment]
@berndruecker pick a time

**Comment by menski** [comment]
BTW if we are good to merge then let's merge it so we can also check it on stage, before we release it tomorrow

**Comment by berndruecker** [comment]
@menski how about 12.00 CET and if all works well Marketing can do the redirects in our afternoon?

**Comment by menski** [comment]
Works for me, but just FYI currently the BPMN loading is broken on https://stage.docs.camunda.io. See my [slack message](https://camunda.slack.com/archives/C026U8GBNSW/p1645599958137049).

**Pull request merged**
