### PR TITLE
Rename Optimize section

### PR DESCRIPTION
**Pull request by HanselIdes**
Integrating Optimize implies a heavy development/IT task
In reality, Camunda Cloud offers turnkey Optimize usage
We should emphasize what Optimize does, rather than have setup a goal into itself

### CODE REVIEW

**Comment by christinaausley** [comment]
I like this new title. This was adjusted in the versioned docs, however. Do you want me to make this adjustment in the current, existing Guides documentation in **docs > guides**? Once this is adjusted and updated in the sidebar.js, I'm sure we'll have a clean build.

**Comment by HanselIdes** [comment]
That sounds great. Please make the adjustment in **docs > guides** @christinaausley  :-)

**Comment by christinaausley** [comment]
@HanselIdes Done! Feel free to review at your convenience.

**Review by christinaausley — DISMISSED** [review]

**Comment by akeller** [comment]
@christinaausley since this renames existing content and the URL, please add a redirect.

**Comment by christinaausley** [comment]
Done @akeller.

**Review by akeller — APPROVED** [review]

**Pull request merged**
