### PR TITLE
chore(desktopModeler/dmn): bring in Camunda 8

### PR DESCRIPTION
**Pull request by MaxTru**
* This will also make this page Modeler agnostic, because Web Modeler will now also support DMN

### CODE REVIEW

**Comment by CatalinaMoisuc** [comment]
@MaxTru lgtm, but 

https://github.com/camunda-cloud/camunda-cloud-documentation/blob/032cb63268495255b255666ff829cc74a15ae102/docs/components/modeler/dmn/img/decision-table.png

can actually show the `Open Overview`, `Edit DRD` buttons because they'll exist also in the Web Modeler, maybe in a slightly different positioning, but will be there.

**Comment by MaxTru** [comment]
> @MaxTru lgtm, but
> 
> https://github.com/camunda-cloud/camunda-cloud-documentation/blob/032cb63268495255b255666ff829cc74a15ae102/docs/components/modeler/dmn/img/decision-table.png
> 
> can actually show the `Open Overview`, `Edit DRD` buttons because they'll exist also in the Web Modeler, maybe in a slightly different positioning, but will be there.

but does it need to? In the end this screen is about the decision table right?

**Comment by CatalinaMoisuc** [comment]
> but does it need to? In the end this screen is about the decision table right?

You're absolutely right.

**Review by CatalinaMoisuc — APPROVED** [review]

**Review by akeller — APPROVED** [review]
LGTM!

@christinaausley FYI - DMN content for Modeler. 

@MaxTru @CatalinaMoisuc - @christinaausley has an OKR around drafting a Guide for DMN, so we might adjust some of this content in the future to cross-link between the Guide and the component documentation.

**Pull request merged**
