### PR TITLE
chore(docs): migrate self-managed Optimize documentation for CCSM fro…

### PR DESCRIPTION
**Pull request by RomanJRW**
…m IAM to Identity

relates to OPT-6066

### CODE REVIEW

**Review by dlavrenuek — APPROVED** [review]
Looks good from technical perspective 👍

**Comment by akeller** [comment]
Are these changes for `release-1.4.0`? If so, please change the merge target.

**Review by christinaausley — APPROVED** [review]
Added a few periods, but LGTM once you adjust the merge target.

**Review by christinaausley — CHANGES_REQUESTED** [review]
Per Amara's comment, are these changes for release-1.4.0? If so, please change the merge target and this will be good to go.

**Comment by RomanJRW** [comment]
@christinaausley - thanks for the review. Conflicts resolved and target branched changed, just waiting for the reapproval to merge 🙂

**Review by christinaausley — APPROVED** [review]

**Pull request merged**
