### PR TITLE
docs(product-manuals): Include Best Practices Blog Posts links (#257)

### PR DESCRIPTION
**Pull request by akeller**
Closes 257 for 2/3 blogs (last blog has not been written).

### CODE REVIEW

**Comment by akeller** [comment]
@berndruecker @falko I put the links in Product Manuals > Zeebe > Technical Concepts. Does this work for you both?

**Comment by berndruecker** [comment]
Hey Amara! I think this does work - but I also wondered if it might make sense to introduce an own top-level link to either something along the lines of "best practices" or "further resources" to make it more visible? 
I don't think it is part of the technical concepts of Zeebe - but if we don't want the hassle of introducing something new here we can still do that for the moment.

**Comment by akeller** [comment]
We could create a section under Product Manuals > Concepts. Visibility-wise, would that work better for you? 

Thinking further into the future, do you think we should include Best Practices within the documentation? Or separate it out like our Camunda Platform docs and Best Practices today? If we want them to be separate in the future, I'm hesitant to have a dedicated page or dedicated section in the docs.

**Comment by berndruecker** [comment]
Spontaneously I like that place ("section under Product Manuals") a bit better!

I don't have a strong opinion on having best practices as part of the docs or separate - the are arguments for both. My two cents: In the docs I think they are easier to find so people are hopefully more aware of the content - which is a good thing. But could lead to another discussion about gating the content for lead-gen :-)

**Comment by akeller** [comment]
I will adjust this PR and create a new section! Thanks for your feedback.

**Comment by akeller** [comment]
@christinaausley can you take a look at these changes for style & grammar?

**Review by christinaausley — COMMENTED** [review]
Clean copy and concise -- no major grammatical/punctual adjustments needed!

**Pull request merged**
