### PR TITLE
Origin/edi

### PR DESCRIPTION
**Pull request by christinaausley**
A review of Camunda Concepts documentation for grammar, punctuation, organization, and terminology. Please excuse the branch name as I accidentally pressed **enter** too soon -- future branch names will be more descriptive, lol.

### CODE REVIEW

**Comment by christinaausley** [comment]
@akeller no rush on review here. Enjoy your weekend as we can touch base on this PR next week.

**Comment by christinaausley** [comment]
It seems I must've pushed one commit from my final Clients adjustments (this is super odd as it compares to my Clients PR, thoughts?) -- feel free to consider this a review of any last-minute adjustments to Clients and a full review of Concepts.

I'm happy to sift through these changes and separate the edits to ensure any Clients changes are solely within the Clients PR -- just let me know. Won't mix up again!

**Comment by akeller** [comment]
My brain went "this is only 8 files, I can do this now" until I realize it was 8 lengthy files 😅 . I'll add this to my list to review next week!

**Comment by christinaausley** [comment]
@akeller Sounds great! Seriously, no hurry.

**Review by akeller — APPROVED** [review]
No additional comments from me, these all look good!

**Pull request merged**
