### PR TITLE
Optimize 3.8 update

### PR DESCRIPTION
**Pull request by megglos**
Missing updates from https://github.com/camunda/camunda-docs-optimize for the release next week.
From here on we will continue writing the docs in this repo and only maintain previous versions in https://github.com/camunda/camunda-docs-optimize .

### CODE REVIEW

**Comment by akeller** [comment]
👋 @megglos don't let the build issues for internal links frustrate you too much. We can likely get those resolved for you.

**Comment by megglos** [comment]
> 👋 @megglos don't let the build issues for internal links frustrate you too much. We can likely get those resolved for you.

give me one more try :D

**Comment by megglos** [comment]
@akeller there is one issue left with an actual direct file download link, which actually works locally, do we need to ignore those in the check?

```
http://172.17.0.2:8080/docs/self-managed/optimize-deployment/migration-update/3.7-to-3.8/
- (27:0) 'en.json...' => http://172.17.0.2:8080/assets/files/differences_localization_370_380-49bf45f0554e5847dbbfac0366a7acf5.diff/ (HTTP 404)
```

**Comment by akeller** [comment]
@megglos I think there is a small tweak we need to make to `.htaccess` and add the file type `.diff`

```
# workaround for 404 with trailing slashes https://github.com/camunda-cloud/camunda-cloud-documentation/issues/403
RewriteRule ^(.*\.(yaml|bpmn|xml|png|jpeg|jpg|yml|svg|graphqls))/$ /$1 [R=301,L]
```

More info: https://github.com/camunda-cloud/camunda-cloud-documentation/pull/453

**Pull request merged**
