### PR TITLE
technical review of best practices according to style guide

### PR DESCRIPTION
**Pull request by christinaausley**
technical review of best practices according to style guide

### CODE REVIEW

**Comment by berndruecker** [comment]
Just making sure - you still collect things in this PR draft - nothing to do right now @christinaausley ?

**Comment by christinaausley** [comment]
@berndruecker yes -- until we feel this PR is nearly ready to merge, we'll keep it as a draft to prevent an accidental merge to master. I'll be editing the best practices in this branch over the next 10 days or so.

**Comment by akeller** [comment]
@christinaausley since there are so many of these (and I'm not sure where you are at as far as how many you've reviewed and how many you have left to review) you always have to option to do PRs in batches to chunk up the work (and avoid as many annoying merge conflicts as possible. Just something to keep in mind. 

And please pull me in if I can help with the merge conflicts or build issues, but I would wait until you want to merge of you may have to chase down a bunch of annoying issues here and there.

**Comment by berndruecker** [comment]
This is now good from my end - @christinaausley: can you have another look and then we can maybe merge this soon (which will allow me to start my renaming branch :-))

**Comment by akeller** [comment]
@christinaausley I just pushed a small fix from another PR that created a conflict here. Let me know when you'd like me to review this PR.

**Comment by akeller** [comment]
@christinaausley can I do a quick skim or are there areas you'd like to specifically draw my attention to here?

**Review by akeller — APPROVED** [review]
LGTM!

**Pull request merged**
