### PR TITLE
changes from Console 0.1.145

### PR DESCRIPTION
**Pull request by ultraschuppi**
.145 likely gets released on monday, screenshots made on preprod

* smaller screenshots wherever possible
* new modeler
* removed duplicates, shared pics are in product manuals - imported into guides

can be reviewed right now, will not automerge

### CODE REVIEW

**Review by ColRad — DISMISSED** [review]
/lgtm

**Review by urbanisierung — DISMISSED** [review]
/lgtm

**Comment by ultraschuppi** [comment]
/hold 

will do some more improvements first

**Review by ColRad — APPROVED** [review]
/lgtm

**Pull request merged**
