### PR TITLE
getting started: clusters are no longer autocreated

### PR DESCRIPTION
**Pull request by ultraschuppi**
part of camunda-cloud/accounts#1504

needs final green light - do not merge

### CODE REVIEW

**Review by christinaausley — APPROVED** [review]
No adjustments on my end!

**Comment by christinaausley** [comment]
Thoughts on the latest commit incorporating the React component @akeller ?

**Comment by akeller** [comment]
> Thoughts on the latest commit incorporating the React component @akeller ?

Looks so good! And thank you @ultraschuppi for the reuse inspiration.

**Comment by ultraschuppi** [comment]
https://github.com/camunda-cloud/accounts/pull/1502 gets merged now and takes the fast track to production. 

therefore: automerge for this PR is activated

**Review by felix-mueller — APPROVED** [review]

**Pull request merged**
