### PR TITLE
Update Operate-Tasklist screenshots for variables panel

### PR DESCRIPTION
**Pull request by huygur**

### CODE REVIEW

**Comment by akeller** [comment]
@menski @santanaluiz was this missed for 1.3? Can you review and merge?

**Comment by menski** [comment]
@santanaluiz will take care of the review, we will push it live after we merged it

**Review by santanaluiz — DISMISSED** [review]
The screenshots look mostly fine. The only point is that we have some inconsistencies.
Like part of them show the "Non production license" and part not.

Seems like not a big deal from my point of view. 
@menski wdyt?

**Comment by menski** [comment]
Let's move forward and fix it with the next round of screenshot updates, I guess in general we should not produce screenshots with the non-prod warning. @santanaluiz maybe something you can communicate into the team

**Comment by menski** [comment]
@huygur if you have time, go ahead

**Comment by menski** [comment]
Thanks you @huygur :+1:

**Review by menski — APPROVED** [review]

**Pull request merged**
