### PR TITLE
Document Zeebe's Priority Election

### PR DESCRIPTION
**Pull request by oleschoenburg**
This PR 
* adds new documentation for priority election
* adds a dedicated page for fixed partitioning.

closes https://github.com/camunda-cloud/zeebe/issues/8341

:warning: Both priority election and fixed partitioning docs now live under self-managed -> zeebe -> configuration. I've decided to move the fixed partitioning docs as they are only available for self-managed and having priority election and fixed partitioning docs close together made sense to me.

Content was mostly adapted from @deepthidevaki's [ZEP006](https://github.com/zeebe-io/enhancements/blob/master/ZEP006-priority-election.md), mistakes are my own.

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
:+1: 

Is the fixed partitioning scheme only linked/accessible via the priority election page and the side bar? We might still want to link to it from the partitions page, where we discuss the partition layout?

EDIT: otherwise no objections, content looks good. I'll defer to our DevEx team if we want to link CCSM content from outside the CCSM section though.

**Review by npepinpe — DISMISSED** [review]

**Comment by oleschoenburg** [comment]
Looks like I'll have to rebase this now that the release-1.3.0 branch is merged.

**Review by christinaausley — APPROVED** [review]
Great work here. Easy to follow along with, clear, and concise. Minor adjustments made in latest commit.

**Comment by oleschoenburg** [comment]
Thank you @christinaausley!

**Pull request merged**
