### PR TITLE
Console API: link to openApi docs

### PR DESCRIPTION
**Pull request by ultraschuppi**
https://github.com/camunda-cloud/console/issues/2840

### CODE REVIEW

**Comment by ultraschuppi** [comment]
@akeller console-prod-push for the new apidocs is still pending - therefor on hold. can be reviewed now

**Comment by akeller** [comment]
@ultraschuppi I got excited until I saw the "No authorization token was found" error on prod 😞  so now I wait :)

**Review by akeller — APPROVED** [review]
Looks good. You have my blessing for when you want to merge this. 🌟

**Comment by akeller** [comment]
When you do want to merge, let me know if you need help correcting the build errors (looks like it's all link-related). Merging in the `master` branch will likely correctly all of these issues.

**Comment by ultraschuppi** [comment]
> When you do want to merge, let me know if you need help correcting the build errors (looks like it's all link-related). Merging in the `master` branch will likely correctly all of these issues.

this PR is ready to ship - https://github.com/camunda-cloud/console/releases/tag/1.3.21 made the changes to production console-wise.

**Pull request merged**
